export default [
    {
        name: "Alerts",
        new: false,
        components: [
            { name: "SuccessPop" },
            { name: "InfoPop" },
            { name: "WarningPop" },
            { name: "ErrorPop" },
            { name: "NotificationPop" },
            { name: "SuccessFullWidth" },
            { name: "InfoFullWidth" },
            { name: "WarningFullWidth" },
            { name: "ErrorFullWidth" },
        ],
    },
    {
        name: "Authentication",
        new: true,
        components: [
            { name: "SimpleLogin" },
            { name: "LoginWithSocialMediaLinks" },
            { name: "LoginWithSideImage" },
            { name: "FullPageWithImage" },
        ],
    },
    {
        name: "Breadcrumbs",
        new: false,
        components: [
            { name: "Simple" },
            { name: "WithArrow" },
            { name: "WithIcons" },
            { name: "FullWidth" },
            { name: "FullWidthWithIcons" },
        ],
    },
    {
        name: "Buttons",
        new: false,
        components: [
            { name: "Primary" },
            { name: "WithIcon" },
            { name: "WithMenu" },
            { name: "Group" },
            { name: "GroupWithIcons" },
        ],
    },
    {
        name: "Cards",
        new: false,
        components: [
            { name: "Article" },
            { name: "ArticleWithSMIcons" },
            { name: "ArticleWithImage" },
            { name: "Product" },
            { name: "ProductWithEvaluation" },
            { name: "SimpleProduct" },
            { name: "Testimonial" },
            { name: "User" },
            { name: "UserWithDetails" },
        ],
    },
    {
        name: "CTA",
        new: true,
        components: [
            { name: "Simple" },
            { name: "Centered" },
            { name: "Grid" },
            { name: "WithForm" },
            { name: "WithImage" },
        ],
    },
    {
        name: "FAQ",
        new: true,
        components: [
            { name: "Centered" },
            { name: "Cards" },
            { name: "Grid" },
            { name: "Collapse" },
            { name: "CollapseWithSideLinks" },
        ],
    },
    {
        name: "Features",
        new: false,
        components: [
            { name: "Simple" },
            { name: "Cards" },
            { name: "Centered" },
            { name: "Media" },
            { name: "GridList" },
            { name: "GridListWithImage" },
            { name: "TrustedBy" },
        ],
    },
    {
        name: "Forms",
        new: false,
        components: [
            { name: "Simple" },
            { name: "Search" },
            { name: "Contact" },
            { name: "SimpleNewsletter" },
            { name: "Newsletter" },
        ],
    },
    {
        name: "Dropdowns",
        new: false,
        components: [
            { name: "Simple" },
            { name: "MultiLevel" },
            { name: "MultiLevelWithIcons" },
            { name: "UserInfo" },
            { name: "UserInfoWithIcons" },
            { name: "Notification" },
        ],
    },
    {
        name: "Navbars",
        new: false,
        components: [
            { name: "Simple" },
            { name: "ECommerce" },
            { name: "WithSearch" },
            { name: "WithAvatar" },
            { name: "WithSocialMediaLinks" },
            { name: "WithCategories" },
        ],
    },
    {
        name: "Heros",
        new: false,
        components: [
            { name: "ECommerce" },
            { name: "WithNewsletterForm" },
            { name: "CenterContent" },
            { name: "CenterContentWithNewsletter" },
            { name: "ImageWithNewsletter" },
            { name: "WithSlide" },
            { name: "WithImage" },
            { name: "WithSideImage" },
            { name: "WithBGImage" },
            { name: "WithPattern" },
        ],
    },
    {
        name: "Sidebar",
        new: false,
        components: [{ name: "WithSearch" }, { name: "WithAvatar" }],
    },
    {
        name: "Sections",
        new: false,
        components: [
            { name: "AboutMe" },
            { name: "ProductsWithSideLinks" },
            { name: "ParagraphWithImage" },
        ],
    },
    {
        name: "Tabs",
        new: false,
        components: [
            { name: "Line" },
            { name: "LineWithIcons" },
            { name: "EndClosed" },
            { name: "EndClosedWithIcons" },
        ],
    },
    {
        name: "Teams",
        new: false,
        components: [
            { name: "Simple" },
            { name: "SideBySide" },
            { name: "WithFilter" },
            { name: "Cards" },
            { name: "Cards2x2" },
            { name: "GridList" },
            { name: "Background" },
        ],
    },
    {
        name: "Pricing",
        new: false,
        components: [
            { name: "Simple" },
            { name: "Checkbox" },
            { name: "CheckboxWithDetails" },
            { name: "SideBySide" },
            { name: "Centered" },
            { name: "WithNavigation" },
            { name: "Popular" },
        ],
    },
    {
        name: "Pagination",
        new: false,
        components: [
            { name: "Simple" },
            { name: "WithArrows" },
            { name: "WithIcons" },
            { name: "Table" },
        ],
    },
    {
        name: "Footers",
        new: false,
        components: [
            { name: "Simple" },
            { name: "WithCta" },
            { name: "WithDetails" },
            { name: "WithLinks" },
            { name: "WithSubscribeForm" },
        ],
    },
];
